# Generated by Django 5.1.2 on 2024-10-17 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_me', '0004_remove_question_question_alter_question_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='technology',
            name='image_name',
            field=models.CharField(default='no_image.png', max_length=100),
        ),
    ]
